In [2]:
import pandas as pd

## Ground Truth

In [3]:
gt_df = pd.read_csv('../data/ground_truth_full.csv')

In [4]:
gt_df.head()

,statement,frequency_heuristic,malicious_account,sensationalism,naive_realism,link
0,A president steeped in constitutional lore mig...,2,0,2,2,https://www.cnn.com/2025/10/20/politics/trump-...
1,"Trump is 'committed' to $2,000 tariff dividend...",0,0,0,1,https://abc7.com/post/trump-is-committed-givin...
2,The longest US government shutdown in history ...,0,0,0,1,https://www.theguardian.com/us-news/2025/nov/1...
3,Add AP News as your preferred source to see mo...,0,0,0,0,https://apnews.com/article/redistricting-gerry...
4,"Key Points Prop 50 passed in California, appro...",1,0,1,0,https://azcapitoltimes.com/news/2025/11/12/pro...

## Base Prompt

model = gemini-3-flash-preview

In [4]:
base = pd.read_csv('../data/base_results.csv')
base.head()

,statement,frequency_heuristic,malicious_account,sensationalism,naive_realism,link
0,A president steeped in constitutional lore mig...,2,2,2,1,https://www.cnn.com/2025/10/20/politics/trump-...
1,"Trump is 'committed' to $2,000 tariff dividend...",1,0,0,1,https://abc7.com/post/trump-is-committed-givin...
2,The longest US government shutdown in history ...,2,2,1,0,https://www.theguardian.com/us-news/2025/nov/1...
3,Add AP News as your preferred source to see mo...,2,2,0,0,https://apnews.com/article/redistricting-gerry...
4,"Key Points Prop 50 passed in California, appro...",2,2,1,0,https://azcapitoltimes.com/news/2025/11/12/pro...

In [5]:
base_freq_acc  = (gt_df["frequency_heuristic"] == base["frequency_heuristic"]).mean()
base_mal_acc   = (gt_df["malicious_account"] == base["malicious_account"]).mean()
base_sens_acc  = (gt_df["sensationalism"] == base["sensationalism"] ).mean()
base_naive_acc = (gt_df["naive_realism"] == base["naive_realism"]).mean()

In [6]:
print("Frequency heuristic accuracy:", base_freq_acc)
print("Malicious account accuracy:", base_mal_acc)
print("Sensationalism accuracy:", base_sens_acc)
print("Naive Realism accuracy:", base_naive_acc)

Frequency heuristic accuracy: 0.3
Malicious account accuracy: 0.1
Sensationalism accuracy: 0.5
Naive Realism accuracy: 0.375

## Chain of Thought

model = gemini-3-flash-preview

In [7]:
cot = pd.read_csv('../data/cot_results.csv')
cot.head()

,statement,frequency_heuristic,malicious_account,sensationalism,naive_realism,link
0,A president steeped in constitutional lore mig...,1,2,2,1,https://www.cnn.com/2025/10/20/politics/trump-...
1,"Trump is 'committed' to $2,000 tariff dividend...",1,2,0,0,https://abc7.com/post/trump-is-committed-givin...
2,The longest US government shutdown in history ...,1,2,1,0,https://www.theguardian.com/us-news/2025/nov/1...
3,Add AP News as your preferred source to see mo...,1,2,0,0,https://apnews.com/article/redistricting-gerry...
4,"Key Points Prop 50 passed in California, appro...",1,2,1,0,https://azcapitoltimes.com/news/2025/11/12/pro...

In [8]:
cot_freq_acc  = (gt_df["frequency_heuristic"] == cot["frequency_heuristic"]).mean()
cot_mal_acc   = (gt_df["malicious_account"] == cot["malicious_account"]).mean()
cot_sens_acc  = (gt_df["sensationalism"] == cot["sensationalism"] ).mean()
cot_naive_acc = (gt_df["naive_realism"] == cot["naive_realism"]).mean()

In [9]:
print("Frequency heuristic accuracy:", cot_freq_acc)
print("Malicious account accuracy:", cot_mal_acc)
print("Sensationalism accuracy:", cot_sens_acc)
print("Naive Realism accuracy:", cot_naive_acc)

Frequency heuristic accuracy: 0.4
Malicious account accuracy: 0.05
Sensationalism accuracy: 0.65
Naive Realism accuracy: 0.375

## In Context Learning

model = gemini-3-flash-preview

In [10]:
icl = pd.read_csv('../data/icl_results.csv')
icl.head()

,statement,frequency_heuristic,malicious_account,sensationalism,naive_realism,link
0,A president steeped in constitutional lore mig...,2,0,2,1,https://www.cnn.com/2025/10/20/politics/trump-...
1,"Trump is 'committed' to $2,000 tariff dividend...",0,0,0,0,https://abc7.com/post/trump-is-committed-givin...
2,The longest US government shutdown in history ...,0,0,1,0,https://www.theguardian.com/us-news/2025/nov/1...
3,Add AP News as your preferred source to see mo...,0,0,0,0,https://apnews.com/article/redistricting-gerry...
4,"Key Points Prop 50 passed in California, appro...",1,0,1,0,https://azcapitoltimes.com/news/2025/11/12/pro...

In [11]:
icl_freq_acc  = (gt_df["frequency_heuristic"] == icl["frequency_heuristic"]).mean()
icl_mal_acc   = (gt_df["malicious_account"] == icl["malicious_account"]).mean()
icl_sens_acc  = (gt_df["sensationalism"] == icl["sensationalism"] ).mean()
icl_naive_acc = (gt_df["naive_realism"] == icl["naive_realism"]).mean()

In [12]:
print("Frequency heuristic accuracy:", icl_freq_acc)
print("Malicious account accuracy:", icl_mal_acc)
print("Sensationalism accuracy:", icl_sens_acc)
print("Naive Realism accuracy:", icl_naive_acc)

Frequency heuristic accuracy: 0.675
Malicious account accuracy: 0.55
Sensationalism accuracy: 0.6
Naive Realism accuracy: 0.45

## Function Calling

model = gemini-3-flash-preview

In [13]:
func_calling = pd.read_csv('../data/function_calling_results.csv')
func_calling.head()

,statement,frequency_heuristic,malicious_account,sensationalism,naive_realism,link
0,A president steeped in constitutional lore mig...,2,0,2,1,https://www.cnn.com/2025/10/20/politics/trump-...
1,"Trump is 'committed' to $2,000 tariff dividend...",1,0,0,0,https://abc7.com/post/trump-is-committed-givin...
2,The longest US government shutdown in history ...,1,2,1,0,https://www.theguardian.com/us-news/2025/nov/1...
3,Add AP News as your preferred source to see mo...,1,2,1,0,https://apnews.com/article/redistricting-gerry...
4,"Key Points Prop 50 passed in California, appro...",1,2,1,0,https://azcapitoltimes.com/news/2025/11/12/pro...

In [14]:
func_calling_freq_acc  = (gt_df["frequency_heuristic"] == func_calling["frequency_heuristic"]).mean()
func_calling_mal_acc   = (gt_df["malicious_account"] == func_calling["malicious_account"]).mean()
func_calling_sens_acc  = (gt_df["sensationalism"] == func_calling["sensationalism"] ).mean()
func_calling_naive_acc = (gt_df["naive_realism"] == func_calling["naive_realism"]).mean()

In [15]:
print("Frequency heuristic accuracy:", func_calling_freq_acc)
print("Malicious account accuracy:", func_calling_mal_acc)
print("Sensationalism accuracy:", func_calling_sens_acc)
print("Naive Realism accuracy:", func_calling_naive_acc)

Frequency heuristic accuracy: 0.525
Malicious account accuracy: 0.125
Sensationalism accuracy: 0.55
Naive Realism accuracy: 0.4

## Fractal Chain of Thought 1 (Gemini 2.5 flash lite)

model = gemini-2.5-flash-lite

In [16]:
fcot1 = pd.read_csv('../data/fcot1_results.csv')

In [17]:
fcot1_freq_acc  = (gt_df["frequency_heuristic"] == fcot1["frequency_heuristic"]).mean()
fcot1_mal_acc   = (gt_df["malicious_account"] == fcot1["malicious_account"]).mean()
fcot1_sens_acc  = (gt_df["sensationalism"] == fcot1["sensationalism"] ).mean()
fcot1_naive_acc = (gt_df["naive_realism"] == fcot1["naive_realism"]).mean()

In [18]:
print("Frequency heuristic accuracy:", fcot1_freq_acc)
print("Malicious account accuracy:", fcot1_mal_acc)
print("Sensationalism accuracy:", fcot1_sens_acc)
print("Naive Realism accuracy:", fcot1_naive_acc)

Frequency heuristic accuracy: 0.2
Malicious account accuracy: 0.775
Sensationalism accuracy: 0.45
Naive Realism accuracy: 0.4

## Fractal Chain of Thought 1 (Gemini 3 Flash)

model = gemini-3-flash-preview

In [19]:
fcot_gem3 = pd.read_csv('../data/fcot_gemini3_results.csv')

In [20]:
gem3_freq_acc  = (gt_df["frequency_heuristic"] == fcot_gem3["frequency_heuristic"]).mean()
gem3_mal_acc   = (gt_df["malicious_account"] == fcot_gem3["malicious_account"]).mean()
gem3_sens_acc  = (gt_df["sensationalism"] == fcot_gem3["sensationalism"] ).mean()
gem3_naive_acc = (gt_df["naive_realism"] == fcot_gem3["naive_realism"]).mean()

In [21]:
print("Frequency heuristic accuracy:", gem3_freq_acc)
print("Malicious account accuracy:", gem3_mal_acc)
print("Sensationalism accuracy:", gem3_sens_acc)
print("Naive Realism accuracy:", gem3_naive_acc)

Frequency heuristic accuracy: 0.55
Malicious account accuracy: 0.225
Sensationalism accuracy: 0.575
Naive Realism accuracy: 0.475

# Fractal Chain of Thought 2

model = gemini-3-flash-preview

In [22]:
fcot_gem3_2 = pd.read_csv('../data/fcot2_results.csv')

In [23]:
gem3_2_freq_acc  = (gt_df["frequency_heuristic"] == fcot_gem3_2["frequency_heuristic"]).mean()
gem3_2_mal_acc   = (gt_df["malicious_account"] == fcot_gem3_2["malicious_account"]).mean()
gem3_2_sens_acc  = (gt_df["sensationalism"] == fcot_gem3_2["sensationalism"] ).mean()
gem3_2_naive_acc = (gt_df["naive_realism"] == fcot_gem3_2["naive_realism"]).mean()

In [24]:
print("Frequency heuristic accuracy:", gem3_2_freq_acc)
print("Malicious account accuracy:", gem3_2_mal_acc)
print("Sensationalism accuracy:", gem3_2_sens_acc)
print("Naive Realism accuracy:", gem3_2_naive_acc)

Frequency heuristic accuracy: 0.425
Malicious account accuracy: 0.825
Sensationalism accuracy: 0.575
Naive Realism accuracy: 0.475

# Fractal Chain of Thought 3

model = gemini-3-flash-preview

In [25]:
fcot3 = pd.read_csv('../data/fcot3_results.csv')

In [26]:
fcot3_freq_acc  = (gt_df["frequency_heuristic"] == fcot3["frequency_heuristic"]).mean()
fcot3_mal_acc   = (gt_df["malicious_account"] == fcot3["malicious_account"]).mean()
fcot3_sens_acc  = (gt_df["sensationalism"] == fcot3["sensationalism"] ).mean()
fcot3_naive_acc = (gt_df["naive_realism"] == fcot3["naive_realism"]).mean()

In [27]:
print("Frequency heuristic accuracy:", fcot3_freq_acc)
print("Malicious account accuracy:", fcot3_mal_acc)
print("Sensationalism accuracy:", fcot3_sens_acc)
print("Naive Realism accuracy:", fcot3_naive_acc)

Frequency heuristic accuracy: 0.525
Malicious account accuracy: 0.95
Sensationalism accuracy: 0.575
Naive Realism accuracy: 0.475

# Instruction Fidelity

model = gemini-3-flash-preview

In [30]:
instruction_fed = pd.read_csv('../data/fcot3_instructionfidelity_results.csv')

In [31]:
if_freq_acc  = (gt_df["frequency_heuristic"] == instruction_fed["frequency_heuristic"]).mean()
if_mal_acc   = (gt_df["malicious_account"] == instruction_fed["malicious_account"]).mean()
if_sens_acc  = (gt_df["sensationalism"] == instruction_fed["sensationalism"] ).mean()
if_naive_acc = (gt_df["naive_realism"] == instruction_fed["naive_realism"]).mean()

In [32]:
print("Frequency heuristic accuracy:", if_freq_acc)
print("Malicious account accuracy:", if_mal_acc)
print("Sensationalism accuracy:", if_sens_acc)
print("Naive Realism accuracy:", if_naive_acc)

Frequency heuristic accuracy: 0.4
Malicious account accuracy: 0.925
Sensationalism accuracy: 0.55
Naive Realism accuracy: 0.35

# FCoT 4

model = gemini-3-flash-preview

In [5]:
fcot4 = pd.read_csv('../data/fcot4.csv')

In [6]:
fcot4_freq_acc  = (gt_df["frequency_heuristic"] == fcot4["frequency_heuristic"]).mean()
fcot4_mal_acc   = (gt_df["malicious_account"] == fcot4["malicious_account"]).mean()
fcot4_sens_acc  = (gt_df["sensationalism"] == fcot4["sensationalism"] ).mean()
fcot4_naive_acc = (gt_df["naive_realism"] == fcot4["naive_realism"]).mean()

In [7]:
print("Frequency heuristic accuracy:", fcot4_freq_acc)
print("Malicious account accuracy:", fcot4_mal_acc)
print("Sensationalism accuracy:", fcot4_sens_acc)
print("Naive Realism accuracy:", fcot4_naive_acc)

Frequency heuristic accuracy: 0.65
Malicious account accuracy: 0.95
Sensationalism accuracy: 0.675
Naive Realism accuracy: 0.4