In [2]:
import pandas as pd
from sklearn.metrics import accuracy_score

## Ground Truth

In [7]:
ground_truth_1 = pd.read_csv('../data/ground_truth.csv')
ground_truth_2 = pd.read_csv('../data/ground_truth_pt2.csv')

gt_df = pd.concat([ground_truth_1, ground_truth_2], ignore_index=True)

In [8]:
gt_df.head()

,statement,frequency_heuristic,malicious_account,sensationalism,naive_realism,link
0,A president steeped in constitutional lore mig...,2,0,2,2,https://www.cnn.com/2025/10/20/politics/trump-...
1,"Trump is 'committed' to $2,000 tariff dividend...",0,0,0,1,https://abc7.com/post/trump-is-committed-givin...
2,The longest US government shutdown in history ...,0,0,0,1,https://www.theguardian.com/us-news/2025/nov/1...
3,Add AP News as your preferred source to see mo...,0,0,0,0,https://apnews.com/article/redistricting-gerry...
4,"Key Points Prop 50 passed in California, appro...",1,0,1,0,https://azcapitoltimes.com/news/2025/11/12/pro...

## Base Prompt

model = gemini-3-flash-preview

In [31]:
base = pd.read_csv('../data/base_results.csv')
base.head()

,statement,frequency_heuristic,malicious_account,sensationalism,naive_realism,link
0,A president steeped in constitutional lore mig...,2,2,2,1,https://www.cnn.com/2025/10/20/politics/trump-...
1,"Trump is 'committed' to $2,000 tariff dividend...",1,0,0,1,https://abc7.com/post/trump-is-committed-givin...
2,The longest US government shutdown in history ...,2,2,1,0,https://www.theguardian.com/us-news/2025/nov/1...
3,Add AP News as your preferred source to see mo...,2,2,0,0,https://apnews.com/article/redistricting-gerry...
4,"Key Points Prop 50 passed in California, appro...",2,2,1,0,https://azcapitoltimes.com/news/2025/11/12/pro...

In [35]:
base_freq_acc  = (gt_df["frequency_heuristic"] == base["frequency_heuristic"]).mean()
base_mal_acc   = (gt_df["malicious_account"] == base["malicious_account"]).mean()
base_sens_acc  = (gt_df["sensationalism"] == base["sensationalism"] ).mean()
base_naive_acc = (gt_df["naive_realism"] == base["naive_realism"]).mean()

In [36]:
print("Frequency heuristic accuracy:", base_freq_acc)
print("Malicious account accuracy:", base_mal_acc)
print("Sensationalism accuracy:", base_sens_acc)
print("Naive Realism accuracy:", base_naive_acc)

Frequency heuristic accuracy: 0.3
Malicious account accuracy: 0.1
Sensationalism accuracy: 0.425
Naive Realism accuracy: 0.375

## Chain of Thought

model = gemini-3-flash-preview

In [45]:
cot = pd.read_csv('../data/cot_results.csv')
cot.head()

,statement,frequency_heuristic,malicious_account,sensationalism,naive_realism,link
0,A president steeped in constitutional lore mig...,1,2,2,1,https://www.cnn.com/2025/10/20/politics/trump-...
1,"Trump is 'committed' to $2,000 tariff dividend...",1,2,0,0,https://abc7.com/post/trump-is-committed-givin...
2,The longest US government shutdown in history ...,1,2,1,0,https://www.theguardian.com/us-news/2025/nov/1...
3,Add AP News as your preferred source to see mo...,1,2,0,0,https://apnews.com/article/redistricting-gerry...
4,"Key Points Prop 50 passed in California, appro...",1,2,1,0,https://azcapitoltimes.com/news/2025/11/12/pro...

In [46]:
cot_freq_acc  = (gt_df["frequency_heuristic"] == cot["frequency_heuristic"]).mean()
cot_mal_acc   = (gt_df["malicious_account"] == cot["malicious_account"]).mean()
cot_sens_acc  = (gt_df["sensationalism"] == cot["sensationalism"] ).mean()
cot_naive_acc = (gt_df["naive_realism"] == cot["naive_realism"]).mean()

In [47]:
print("Frequency heuristic accuracy:", cot_freq_acc)
print("Malicious account accuracy:", cot_mal_acc)
print("Sensationalism accuracy:", cot_sens_acc)
print("Naive Realism accuracy:", cot_naive_acc)

Frequency heuristic accuracy: 0.4
Malicious account accuracy: 0.05
Sensationalism accuracy: 0.575
Naive Realism accuracy: 0.375

## In Context Learning

model = gemini-3-flash-preview

In [38]:
icl = pd.read_csv('../data/icl_results.csv')
icl.head()

,statement,frequency_heuristic,malicious_account,sensationalism,naive_realism,link
0,A president steeped in constitutional lore mig...,2,0,2,1,https://www.cnn.com/2025/10/20/politics/trump-...
1,"Trump is 'committed' to $2,000 tariff dividend...",0,0,0,0,https://abc7.com/post/trump-is-committed-givin...
2,The longest US government shutdown in history ...,0,0,1,0,https://www.theguardian.com/us-news/2025/nov/1...
3,Add AP News as your preferred source to see mo...,0,0,0,0,https://apnews.com/article/redistricting-gerry...
4,"Key Points Prop 50 passed in California, appro...",1,0,1,0,https://azcapitoltimes.com/news/2025/11/12/pro...

In [39]:
icl_freq_acc  = (gt_df["frequency_heuristic"] == icl["frequency_heuristic"]).mean()
icl_mal_acc   = (gt_df["malicious_account"] == icl["malicious_account"]).mean()
icl_sens_acc  = (gt_df["sensationalism"] == icl["sensationalism"] ).mean()
icl_naive_acc = (gt_df["naive_realism"] == icl["naive_realism"]).mean()

In [40]:
print("Frequency heuristic accuracy:", icl_freq_acc)
print("Malicious account accuracy:", icl_mal_acc)
print("Sensationalism accuracy:", icl_sens_acc)
print("Naive Realism accuracy:", icl_naive_acc)

Frequency heuristic accuracy: 0.675
Malicious account accuracy: 0.55
Sensationalism accuracy: 0.575
Naive Realism accuracy: 0.45

## Function Calling

model = gemini-3-flash-preview

In [42]:
func_calling = pd.read_csv('../data/function_calling_results.csv')
func_calling.head()

,statement,frequency_heuristic,malicious_account,sensationalism,naive_realism,link
0,A president steeped in constitutional lore mig...,2,0,2,1,https://www.cnn.com/2025/10/20/politics/trump-...
1,"Trump is 'committed' to $2,000 tariff dividend...",1,0,0,0,https://abc7.com/post/trump-is-committed-givin...
2,The longest US government shutdown in history ...,1,2,1,0,https://www.theguardian.com/us-news/2025/nov/1...
3,Add AP News as your preferred source to see mo...,1,2,1,0,https://apnews.com/article/redistricting-gerry...
4,"Key Points Prop 50 passed in California, appro...",1,2,1,0,https://azcapitoltimes.com/news/2025/11/12/pro...

In [43]:
func_calling_freq_acc  = (gt_df["frequency_heuristic"] == func_calling["frequency_heuristic"]).mean()
func_calling_mal_acc   = (gt_df["malicious_account"] == func_calling["malicious_account"]).mean()
func_calling_sens_acc  = (gt_df["sensationalism"] == func_calling["sensationalism"] ).mean()
func_calling_naive_acc = (gt_df["naive_realism"] == func_calling["naive_realism"]).mean()

In [44]:
print("Frequency heuristic accuracy:", func_calling_freq_acc)
print("Malicious account accuracy:", func_calling_mal_acc)
print("Sensationalism accuracy:", func_calling_sens_acc)
print("Naive Realism accuracy:", func_calling_naive_acc)

Frequency heuristic accuracy: 0.525
Malicious account accuracy: 0.125
Sensationalism accuracy: 0.5
Naive Realism accuracy: 0.4

## Fractal Chain of Thought 1

model = gemini-2.5-flash-lite

In [21]:
fcot_1 = pd.read_csv('../data/fcot1_results.csv')

In [22]:
freq_acc  = (gt_df["frequency_heuristic"] == fcot_1["frequency_heuristic"]).mean()
mal_acc   = (gt_df["malicious_account"] == fcot_1["malicious_account"]).mean()
sens_acc  = (gt_df["sensationalism"] == fcot_1["sensationalism"] ).mean()
naive_acc = (gt_df["naive_realism"] == fcot_1["naive_realism"]).mean()

In [23]:
print("Frequency heuristic accuracy:", freq_acc)
print("Malicious account accuracy:", mal_acc)
print("Sensationalism accuracy:", sens_acc)
print("Naive Realism accuracy:", naive_acc)

Frequency heuristic accuracy: 0.2
Malicious account accuracy: 0.775
Sensationalism accuracy: 0.45
Naive Realism accuracy: 0.4

In [26]:
og_fcot = gt_df.head(20)

In [27]:
freq_acc  = (ground_truth_1["frequency_heuristic"] == og_fcot["frequency_heuristic"]).mean()
mal_acc   = (ground_truth_1["malicious_account"] == og_fcot["malicious_account"]).mean()
sens_acc  = (ground_truth_1["sensationalism"] == og_fcot["sensationalism"] ).mean()
naive_acc = (ground_truth_1["naive_realism"] == og_fcot["naive_realism"]).mean()

In [24]:
print("Frequency heuristic accuracy:", freq_acc)
print("Malicious account accuracy:", mal_acc)
print("Sensationalism accuracy:", sens_acc)
print("Naive Realism accuracy:", naive_acc)

Frequency heuristic accuracy: 0.05
Malicious account accuracy: 0.55
Sensationalism accuracy: 0.7
Naive Realism accuracy: 0.45

In [28]:
freq_scores = pd.DataFrame({
    'link': gt_df['link'],
    'ground_truth_fh': gt_df['frequency_heuristic'],
    'agent_fh': fcot_1['frequency_heuristic']
})

In [29]:
freq_scores

,link,ground_truth_fh,agent_fh
0,https://www.cnn.com/2025/10/20/politics/trump-...,2,2
1,https://abc7.com/post/trump-is-committed-givin...,0,2
2,https://www.theguardian.com/us-news/2025/nov/1...,0,1
3,https://apnews.com/article/redistricting-gerry...,0,1
4,https://azcapitoltimes.com/news/2025/11/12/pro...,1,2
5,https://abcnews.go.com/Politics/house-vote-ful...,0,2
6,https://www.nbcnews.com/politics/politics-news...,0,1
7,https://www.bbc.com/news/articles/c4gpnz05kr8o,1,2
8,https://calmatters.org/commentary/2025/11/dana...,0,2
9,https://www.kff.org/racial-equity-and-health-p...,0,2
10,https://www.nytimes.com/2025/11/19/opinion/tru...,0,2
11,https://www.dailywire.com/news/musk-reveals-sh...,1,2
12,https://dppa.un.org/en/mtg-sc-10027-asg-pobee-...,1,2
13,https://www.cbsnews.com/news/epstein-accusers-...,0,2
14,https://www.dailymail.co.uk/sport/mlb/article-...,1,2
15,https://www.rollingstone.com/politics/politics...,1,2
16,https://www.vanityfair.com/news/story/gavin-ne...,1,2
17,https://www.scrippsnews.com/politics/immigrati...,1,2
18,https://www.foxnews.com/politics/trump-gave-ma...,1,2
19,https://www.politico.com/news/2025/11/30/jerse...,1,2
20,https://www.washingtonpost.com/nation/2026/01/...,0,0
21,https://abcnews.go.com/US/person-shot-incident...,2,2
22,https://www.pbs.org/newshour/politics/watch-li...,0,2
23,https://www.theguardian.com/us-news/2026/jan/2...,1,2
24,https://www.theguardian.com/technology/2025/oc...,1,2
25,https://www.the-sun.com/money/15848488/social-...,2,2
26,https://www.investopedia.com/5-things-to-know-...,0,2
27,https://www.reuters.com/world/asia-pacific/tru...,0,2
28,https://www.gov.uk/government/news/pm-call-wit...,0,2
29,https://www.aljazeera.com/economy/2026/1/27/cb...,2,2
30,https://timesofindia.indiatimes.com/sports/wwe...,0,0
31,https://www.reuters.com/world/europe/several-k...,0,1
32,https://www.who.int/news/item/24-01-2026-who-s...,1,1
33,https://en.wikipedia.org/wiki/2026_Minnesota_g...,1,2
34,https://en.wikipedia.org/wiki/2026_Internet_bl...,2,2
35,https://en.wikipedia.org/wiki/2026_Mark_Carney...,1,2
36,https://www.finance.senate.gov/ranking-members...,0,2
37,https://www.theguardian.com/us-news/2026/feb/0...,1,2
38,https://inforrm.org/2026/01/12/law-and-media-r...,0,2
39,https://sof.news/update/20260126/,0,2